---
- name: Install and Configure Papirus Folders
  become: yes
  block:
    - name: Check if Papirus Folders tool is installed
      stat:
        path: /usr/bin/papirus-folders
      register: papirus_folders_installed

    - name: Install Papirus Folders tool if not installed
      shell: wget -qO- https://git.io/papirus-folders-install | sh
      args:
        creates: /usr/bin/papirus-folders
      when: papirus_folders_installed.stat.exists == false

    - name: Configure Papirus Folders color to paleorange
      command: papirus-folders -C paleorange --theme Papirus
      when: papirus_folders_installed.stat.exists == true
