---
- name: Install and Configure Icon and Theme (Papirus and Arc)
  become: yes
  block:
    - name: Check if Papirus icon theme is installed
      stat:
        path: "/usr/share/icons/Papirus"
      register: papirus_icon_theme_installed

    - name: Install Papirus icon theme if not installed
      apt:
        name: papirus-icon-theme
        state: present
      when: papirus_icon_theme_installed.stat.exists == false

    - name: Check if Arc theme is installed
      stat:
        path: "/usr/share/themes/Arc"
      register: arc_theme_installed

    - name: Install Arc theme if not installed
      apt:
        name: arc-theme
        state: present
      when: arc_theme_installed.stat.exists == false

    - name: Set default icon theme to Papirus
      shell: |
        export DISPLAY=:0
        xfconf-query -c xsettings -p /Net/IconThemeName -s Papirus


    - name: Set default GTK theme to Arc
      shell: |
        export DISPLAY=:0
        xfconf-query -c xsettings -p /Net/ThemeName -s Arc