- hosts: all
  gather_facts: false
  tasks:
    - name: Check if Papirus icon theme is installed
      command: dpkg-query -l papirus-icon-theme
      register: papirus_icon_theme_installed
      ignore_errors: true

    - name: Ensure Papirus icon theme is installed
      apt:
        name: papirus-icon-theme
        state: present
      when: papirus_icon_theme_installed.rc != 0

    - name: Ensure Arc theme is installed
      apt:
        name: arc-theme
        state: present

    - name: Set default icon theme to Papirus
      command: gsettings set org.gnome.desktop.interface icon-theme 'Papirus'
      when: papirus_icon_theme_installed.rc == 0

    - name: Set default theme to Arc-Lighter
      command: gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Lighter'

    - name: Verify all tasks succeeded
      debug:
        msg: "All theme setup tasks completed successfully."
