---
- name: Configure Icons and Themes
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Ensure Papirus icon theme is installed
      apt:
        name: papirus-icon-theme
        state: present

    - name: Ensure Arc theme is installed
      apt:
        name: arc-theme
        state: present

    - name: Set default icon theme to Papirus
      command: gsettings set org.gnome.desktop.interface icon-theme 'Papirus'

    - name: Set default GTK theme to Arc-Lighter
      command: gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Lighter'
