- tasks:
    - name: Ensure Papirus icon theme is installed
      apt:
        name: papirus-icon-theme
        state: present

    - name: Ensure Arc theme is installed
      apt:
        name: arc-theme
        state: present

    - name: Install Papirus Folders tool
      shell: wget -qO- https://git.io/papirus-folders-install | sh
      args:
        creates: /usr/bin/papirus-folders

    - name: Configure Papirus Folders color to paleorange
      command: papirus-folders -C paleorange --theme Papirus
      when: papirus_folders_installed.stat.exists
      register: papirus_folders_config

    - name: Check if Papirus Folders tool is installed
      stat:
        path: /usr/bin/papirus-folders
      register: papirus_folders_installed

    - name: Set default icon theme to Papirus
      command: gsettings set org.gnome.desktop.interface icon-theme 'Papirus'
      when: papirus_icon_theme_installed is defined and papirus_icon_theme_installed is true

    - name: Set default theme to Arc-Lighter
      command: gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Lighter'
      when: arc_theme_installed is defined and arc_theme_installed is true

    - name: Verify Papirus icon theme installation
      shell: dpkg -l | grep -q papirus-icon-theme && echo true || echo false
      register: papirus_icon_theme_installed

    - name: Verify Arc theme installation
      shell: dpkg -l | grep -q arc-theme && echo true || echo false
      register: arc_theme_installed
