---
  - name: Install Icons and Themes
    gather_facts: false
    tasks:
      - name: Ensure Papirus icon theme is installed
        apt:
          name: papirus-icon-theme
          state: present

      - name: Ensure Arc theme is installed
        apt:
          name: arc-theme
          state: present

      - name: Set default icon theme to Papirus
        command: gsettings set org.gnome.desktop.interface icon-theme 'Papirus'

      - name: Set default theme to Arc-Lighter
        command: gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Lighter'

      - name: Verify all tasks succeeded
        debug:
          msg: "All theme setup tasks completed successfully."

      - name: Include Papirus Folders setup
        include_tasks: 88_setup_papirus_folders.yml
        when: not ansible_failed_tasks
