---
    - name: Load package manager
      set_fact:
        pkg_manager: "apt"

    - name: Define applications
      set_fact:
        applications:
          - autoconf
          - gvfs
          - gvfs-common
          - gvfs-daemons
          - gvfs-libs
          - libmtp-dev
          - gvfs-backends
          - apt-transport-https
          - htop
          - gnome-disk-utility
          - apparmor
          - asciinema
          - axel
          - curl
          - fonts-lyx
          - galculator
          - gtk-update-icon-cache
          - keepassxc
          - locate
          - lsb-release
          - menulibre
          - neofetch
          - net-tools
          - transmission-gtk
          - unrar-free
          - unzip
          - papirus-icon-theme
          - arc-theme
          - xfce4-panel-profiles
          - copyq

    - name: Update repositories
      become: yes
      apt:
        update_cache: yes

    - name: Install base applications
      become: yes
      apt:
        name: "{{ item }}"
      with_items: "{{ applications }}"
