---
- name: Copiar chaves SSH
  hosts: qxdc
  become: true
  become_method: sudo
  become_user: root

  vars_prompt:
    - name: ansible_user
      prompt: "Digite seu usuário SSH"
      private: no
    - name: ansible_ssh_pass
      prompt: "Digite sua senha SSH"
      private: yes
    - name: ansible_become_pass
      prompt: "Digite sua senha SUDO"
      private: yes

  tasks:
    - name: Garantir que o diretório ~/.ssh existe no servidor de aplicação
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: '0700'
      become_user: "{{ ansible_user }}"

    - name: Copiar chaves SSH para o servidor de aplicação
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "~/.ssh/"
        mode: '0600'
      with_fileglob:
        - ~/.ssh/*
      become_user: "{{ ansible_user }}"

    - name: Adicionar chaves ao agente SSH no servidor de aplicação
      ansible.builtin.shell:
        cmd: ssh-add ~/.ssh/{{ item }}
      with_fileglob:
        - "~/.ssh/*"
      become_user: "{{ ansible_user }}"
