---
- name: Configurar hostapd
  hosts: debian_servers
  become: true
  tasks:
    - name: Instalar hostapd e dnsmasq
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - hostapd
        - dnsmasq

    - name: Desativar serviços
      systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - hostapd
        - dnsmasq

    - name: Configurar interface de rede
      lineinfile:
        path: /etc/network/interfaces
        line: "iface wlan0 inet static\n  address 192.168.1.1\n  netmask 255.255.255.0"
      notify:
        - Reiniciar serviços de rede

  handlers:
    - name: Reiniciar serviços de rede
      service:
        name: networking
        state: restarted
