---
- name: Configure Debian Server to Join Windows Active Directory Domain
  hosts: debian_servers
  become: yes

  tasks:
    - name: Instalar pacotes requeridos
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pexpect
        - realmd
        - sssd
        - sssd-tools
        - libnss-sss
        - libpam-sss
        - adcli
        - samba-common-bin
        - oddjob
        - oddjob-mkhomedir
        - packagekit

    - name: Definir configurações de DNS
      copy:
        content: Definir o domínio do Active Directory
          domain SEU_LDAP.SEU_CN
          search SEU_LDAP.SEU_CN
          nameserver SEU_LDAP_IP
          nameserver SEU_IP_DNS
        dest: /etc/resolv.conf

    - name: 
      command: realm discover SEU_LDAP.SEU_CN

    - name: Ingressar no domínio do Active Directory
      expect:
        command: realm join -U 'Administrator' SEU_LDAP.SEU_CN
        responses:
          Senha para Administrator: "SUA_SENHA"
        timeout: 60  # Aumentar o timeout para 60 sec
      vars:
        ansible_become_password: SUA_SENHA
      args:
        creates: /etc/krb5.keytab


    - name: Verifique as informações do usuário AD
      command: id SEU_USUARIO@SEU_LDAP.SEU_CN
      register: ad_user_info

    - name: Adicionar configuração pam_mkhomedir
      lineinfile:
        path: /etc/pam.d/common-session
        line: "session optional        pam_mkhomedir.so skel=/etc/skel umask=077"

    - name: Configure o sssd para omitir o nome de domínio
      lineinfile:
        path: /etc/sssd/sssd.conf
        line: "use_fully_qualified_names = False"
      notify: Restart sssd

  handlers:
    - name: Reiniciar sssd
      systemd:
        name: sssd
        state: restarted
        daemon_reload: yes

- name: Configurar sssd para UID/GID fixo
  hosts: debian_servers
  become: yes

  tasks:
    - name: Configurar sssd para UID/GID fixo
      blockinfile:
        path: /etc/sssd/sssd.conf
        block: |
          ldap_id_mapping = False
          ldap_user_uid_number = uidNumber
          ldap_user_gid_number = gidNumber
      notify: Clear sssd cache and restart sssd

  handlers:
    - name: Limpe o cache do SSD e reinicie o SSD
      command: "{{ item }}"
      loop:
        - rm -f /var/lib/sss/db/*
        - systemctl restart sssd
