- hosts: qxdc
  gather_facts: false
  tasks:
    - name: Execute QXDC Playbooks
      include_tasks: "{{ qxdc_task_file }}"
      loop: "{{ query('fileglob', 'qxdc/*.yml') | sort | reverse }}"
      loop_control:
        loop_var: qxdc_task_file  # Define um nome diferente para a variável
